### ISSUE TITLE
提示SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by nnssz** [raawaa/jav-scrapy#13]
在我的linode VPS ubuntu X64 下运行出现错误。非IT人士一枚，请指导，谢谢！

root@ubuntu:~/jav-scrapy# jav -s ipz-634 -o ~/magnet.txt

/root/jav-scrapy/jav.js:16
const baseUrl = 'https://www.javbus.me';
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by raawaa** [comment]
请问Node.js版本。

**Comment by Kiris-tingna** [comment]
使用 --harmony @nnssz
