### ISSUE TITLE
ubuntu 20.04 运行时报错

### ISSUE THREAD

**Issue by twinfishxixi** [raawaa/jav-scrapy#55]
系统前段时间全新安装后，又重新安装了本工具，但是在运行时出现报错，这个问题在`ubuntu 18.04`时没有出现过，不知道是`javbus`更改了网页结构还是自己的系统的问题，目前`nodejs`版本是`10.19.0`，请大神指教，报错情况如下：
```
$ jav -s KTB -p 20 -o /home/twinfish/movie/Japan/foto/KTB -x http://127.0.0.1:8118
========== 获取资源站点：https://www.javbus.com/ ==========
并行连接数： 20        连接超时设置： 30 秒
磁链保存位置:  /home/twinfish/movie/Japan/foto/KTB
代理服务器:  http://127.0.0.1:8118
正处理以下番号影片...
KTB-054,KTB-053,KTB-052,KTB-051,KTB-050,KTB-049,KTB-048,KTB-047,KTB-046,KTB-045,KTB-044,KTB-043,KTB-042,KTB-041,KTB-040,KTB-039,KTB-038,KTB-037,KTB-036,KTB-035,KTB-034,KTB-033,KTB-032,KTB-031,KTB-030,KTB-029,KTB-028,KTB-026,KTB-027,KTB-025
/media/data2/download/software/net/jav-scrapy/jav.js:204
    let img = img_r[1];
                   ^

TypeError: Cannot read property '1' of null
    at parse (/media/data2/download/software/net/jav-scrapy/jav.js:204:20)
    at Request._callback (/media/data2/download/software/net/jav-scrapy/jav.js:234:28)
    at Request.self.callback (/media/data2/download/software/net/jav-scrapy/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/media/data2/download/software/net/jav-scrapy/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/media/data2/download/software/net/jav-scrapy/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
```

**Comment by raawaa** [comment]
我这两天看一下。因为本职工作不是写程序的，可能要再去复习一下js。☺️

**Comment by twinfishxixi** [comment]
哈哈，好的，感谢！～
另外，看到主程序代码也有很久没有更新了，不知道是否还继续维护哦？

**Comment by raawaa** [comment]
不会更新了，最多出现力所能及的小bug修复一下。

**Comment by raawaa** [comment]
报错的问题已经修复。重新pull一下再试试。
